[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "postgresql"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[variables]
PYTHONUNBUFFERED = "1"

[start]
cmd = "python -m app.run"
